t2sdk.lo: /Users/caizixin/source/php-t2sdk-ext/t2sdk.cpp
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/Users/caizixin/source/php-t2sdk-ext $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /Users/caizixin/source/php-t2sdk-ext/t2sdk.cpp -o t2sdk.lo 
source/T2Connection.lo: /Users/caizixin/source/php-t2sdk-ext/source/T2Connection.cpp
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/Users/caizixin/source/php-t2sdk-ext $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /Users/caizixin/source/php-t2sdk-ext/source/T2Connection.cpp -o source/T2Connection.lo 
source/SecuTrade.lo: /Users/caizixin/source/php-t2sdk-ext/source/SecuTrade.cpp
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/Users/caizixin/source/php-t2sdk-ext $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /Users/caizixin/source/php-t2sdk-ext/source/SecuTrade.cpp -o source/SecuTrade.lo 
source/SecuMD.lo: /Users/caizixin/source/php-t2sdk-ext/source/SecuMD.cpp
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/Users/caizixin/source/php-t2sdk-ext $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /Users/caizixin/source/php-t2sdk-ext/source/SecuMD.cpp -o source/SecuMD.lo 
Common/tool.lo: /Users/caizixin/source/php-t2sdk-ext/Common/tool.cpp
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/Users/caizixin/source/php-t2sdk-ext $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /Users/caizixin/source/php-t2sdk-ext/Common/tool.cpp -o Common/tool.lo 
Common/analyStr.lo: /Users/caizixin/source/php-t2sdk-ext/Common/analyStr.cpp
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/Users/caizixin/source/php-t2sdk-ext $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /Users/caizixin/source/php-t2sdk-ext/Common/analyStr.cpp -o Common/analyStr.lo 
$(phplibdir)/t2sdk.la: ./t2sdk.la
	$(LIBTOOL) --mode=install cp ./t2sdk.la $(phplibdir)

./t2sdk.la: $(shared_objects_t2sdk) $(T2SDK_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_t2sdk) $(T2SDK_SHARED_LIBADD)

